AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-todo

Globals:
  Function:
    Timeout: 3

Resources:
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/createTask.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/getTask.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: get
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/updateTask.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UpdateTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/deleteTask.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: delete
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: handlers/listTasks.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ListTasksApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
      Environment:
        Variables:
          TASKS_TABLE: !Ref TasksTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable

  TasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: taskId
        Type: String
      TableName: Tasks

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  TasksTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref TasksTable