AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-todo

Globals:
  Function:
    Timeout: 3

Resources:
  TodoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/todoHandler.lambdaHandler  # adjust based on your export
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        TodoApi:
          Type: Api
          Properties:
            Path: /todo
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/todoHandler.ts
          
Outputs:
  TodoApi:
    Description: "API Gateway endpoint URL for Todo function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/todo/"
  TodoFunction:
    Description: "Todo Lambda Function ARN"
    Value: !GetAtt TodoFunction.Arn
  TodoFunctionIamRole:
    Description: "Implicit IAM Role created for Todo function"
    Value: !GetAtt TodoFunctionRole.Arn
