AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-todo

Globals:
  Function:
    Timeout: 3

Resources:
  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/createTask.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CreateTaskApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/createTask.ts

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/getTask.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        GetTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/getTask.ts

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/updateTask.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        UpdateTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/updateTask.ts

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/deleteTask.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        DeleteTaskApi:
          Type: Api
          Properties:
            Path: /tasks/{taskId}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/deleteTask.ts

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: src/handlers/listTasks.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        ListTasksApi:
          Type: Api
          Properties:
            Path: /tasks
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/handlers/listTasks.ts

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
